//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TellNumInJpn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TellNumInJpn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,あ;i,い;u,う;e,え;o,お;ka,か;ki,き;ku,く;ke,け;ko,こ;sa,さ;shi,し;su,す;se,せ;so,そ;ta,た;chi,ち;tsu,つ;te,て;to,と;na,な;ni,に;nu,ぬ;ne,ね;no,の;ha,は;hi,ひ;fu,ふ;he,へ;ho,ほ;ma,ま;mi,み;mu,む;me,め;mo,も;ya,や;yu,ゆ;yo,よ;ra,ら;ri,り;ru,る;re,れ;ro,ろ;wa,わ;wo,を;n,ん;ga,が;gi,ぎ;gu,ぐ;ge,げ;go,ご;za,ざ;ji,じ;zu,ず;ze,ぜ;zo,ぞ;da,だ;dzi,ぢ;dzu,づ;de,で;do,ど;ba,ば;bi,び;bu,ぶ;be,べ;bo,ぼ;pa,ぱ;pi,ぴ;pu,ぷ;pe,ぺ;po,ぽ;.
        /// </summary>
        internal static string romajihira {
            get {
                return ResourceManager.GetString("romajihira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been a long time I didn&apos;t develop anything since I have the new PC, too many things to try with such powerful spec (compared to my netbook).
        ///
        ///Since I&apos;m learning Japanese recently, I decide to make a program about it, so this is it, &quot;Tell number in Japanese&quot;.
        ///
        ///Well, this time is a bit different, I use C# instead of VB.NET that I used for most of my previous projects, as I&apos;m kinda bored with VB.NET.
        ///
        ///I hope you guys enjoy this program. You may use my code in your project as long as you put my nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string somewords {
            get {
                return ResourceManager.GetString("somewords", resourceCulture);
            }
        }
    }
}
